import { Facility, FuneralCompany } from './types';

export const FUNERAL_COMPANIES: FuneralCompany[] = [
  {
    id: 'fc_new_1',
    name: '프리드라이프',
    rating: 5.0,
    reviewCount: 990,
    imageUrl: '/images/logos/fc_new_1.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_2',
    name: '교원라이프',
    rating: 5.0,
    reviewCount: 980,
    imageUrl: '/images/logos/fc_new_2.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_3',
    name: '대명스테이션',
    rating: 4.9,
    reviewCount: 970,
    imageUrl: '/images/logos/fc_new_3.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_4',
    name: '더케이예다함',
    rating: 4.9,
    reviewCount: 960,
    imageUrl: '/images/logos/fc_new_4.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_5',
    name: '보람상조개발',
    rating: 4.9,
    reviewCount: 950,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_6',
    name: '보람상조라이프',
    rating: 4.9,
    reviewCount: 940,
    imageUrl: '/images/logos/fc_new_6.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_7',
    name: '부모사랑',
    rating: 4.9,
    reviewCount: 930,
    imageUrl: '/images/logos/fc_new_7.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_8',
    name: '보람상조리더스',
    rating: 4.8,
    reviewCount: 920,
    imageUrl: '/images/logos/fc_new_8.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_9',
    name: '더피플라이프',
    rating: 4.8,
    reviewCount: 910,
    imageUrl: '/images/logos/fc_new_9.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_10',
    name: '더리본',
    rating: 4.8,
    reviewCount: 900,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_11',
    name: '보람상조피플',
    rating: 4.8,
    reviewCount: 890,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_12',
    name: '효원상조',
    rating: 4.8,
    reviewCount: 880,
    imageUrl: '/images/logos/fc_new_12.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_13',
    name: '늘곁애라이프온',
    rating: 4.7,
    reviewCount: 870,
    imageUrl: '/images/logos/fc_new_13.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_14',
    name: '평화누리',
    rating: 4.7,
    reviewCount: 860,
    imageUrl: '/images/logos/fc_new_14.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_15',
    name: 'SJ산림조합상조',
    rating: 4.7,
    reviewCount: 850,
    imageUrl: '/images/logos/fc_new_15.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_16',
    name: '보람상조애니콜',
    rating: 4.7,
    reviewCount: 840,
    imageUrl: '/images/logos/fc_new_16.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_17',
    name: '에이치디투어존',
    rating: 4.7,
    reviewCount: 830,
    imageUrl: '/images/logos/fc_new_17.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_18',
    name: '휴먼라이프',
    rating: 4.6,
    reviewCount: 820,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_19',
    name: '제이케이',
    rating: 4.6,
    reviewCount: 810,
    imageUrl: '/images/logos/fc_new_19.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_20',
    name: '대노복지사업단',
    rating: 4.6,
    reviewCount: 800,
    imageUrl: '/images/logos/fc_new_20.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_21',
    name: '경우라이프',
    rating: 4.6,
    reviewCount: 790,
    imageUrl: '/images/logos/fc_new_21.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_22',
    name: '다온플랜',
    rating: 4.6,
    reviewCount: 780,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_23',
    name: '에이플러스라이프',
    rating: 4.5,
    reviewCount: 770,
    imageUrl: '/images/logos/fc_new_23.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_24',
    name: '현대에스라이프',
    rating: 4.5,
    reviewCount: 760,
    imageUrl: '/images/logos/fc_new_24.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_25',
    name: '한라상조',
    rating: 4.5,
    reviewCount: 750,
    imageUrl: '/images/logos/fc_new_25.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_26',
    name: '보람상조실로암',
    rating: 4.5,
    reviewCount: 740,
    imageUrl: '/images/logos/fc_new_26.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_27',
    name: '디에스라이프',
    rating: 4.5,
    reviewCount: 730,
    imageUrl: '/images/logos/fc_new_27.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_28',
    name: '엘비라이프',
    rating: 4.4,
    reviewCount: 720,
    imageUrl: '/images/logos/fc_new_28.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_29',
    name: '금호라이프',
    rating: 4.4,
    reviewCount: 710,
    imageUrl: '/images/logos/fc_new_29.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_30',
    name: '크리스찬상조',
    rating: 4.4,
    reviewCount: 700,
    imageUrl: '/images/logos/fc_new_30.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_31',
    name: '우정라이프',
    rating: 4.4,
    reviewCount: 690,
    imageUrl: '/images/logos/fc_new_31.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_32',
    name: '보훈상조',
    rating: 4.4,
    reviewCount: 680,
    imageUrl: '/images/logos/fc_new_32.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_33',
    name: '용인공원라이프',
    rating: 4.3,
    reviewCount: 670,
    imageUrl: '/images/logos/fc_new_33.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_34',
    name: '불국토',
    rating: 4.3,
    reviewCount: 660,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_35',
    name: '대한라이프보증',
    rating: 4.3,
    reviewCount: 650,
    imageUrl: '/images/logos/fc_new_35.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_36',
    name: '우리제주상조',
    rating: 4.3,
    reviewCount: 640,
    imageUrl: '/images/logos/fc_new_36.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_37',
    name: '유토피아퓨처',
    rating: 4.3,
    reviewCount: 630,
    imageUrl: '/images/logos/fc_new_37.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_38',
    name: '다나상조',
    rating: 4.2,
    reviewCount: 620,
    imageUrl: '/images/logos/fc_new_38.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_39',
    name: '아가페라이프',
    rating: 4.2,
    reviewCount: 610,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_40',
    name: '웰리빙라이프',
    rating: 4.2,
    reviewCount: 600,
    imageUrl: '/images/logos/fc_new_40.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_41',
    name: '삼육리더스라이프',
    rating: 4.2,
    reviewCount: 590,
    imageUrl: '/images/logos/fc_new_41.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_42',
    name: '우리관광',
    rating: 4.2,
    reviewCount: 580,
    imageUrl: '/images/logos/fc_new_42.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_43',
    name: '세종라이프',
    rating: 4.1,
    reviewCount: 570,
    imageUrl: '/images/logos/fc_new_43.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_44',
    name: '삼우라이프',
    rating: 4.1,
    reviewCount: 560,
    imageUrl: '/images/logos/fc_new_44.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_45',
    name: '태양라이프',
    rating: 4.1,
    reviewCount: 550,
    imageUrl: '/images/logos/fc_new_45.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  },
  {
    id: 'fc_new_46',
    name: '새부산상조',
    rating: 4.1,
    reviewCount: 540,
    imageUrl: '/images/logos/fc_new_46.png',
    description: '믿을 수 있는 상조 서비스',
    features: ["전국 의전망", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["회원 전용 혜택"]
  }
];

export const FACILITIES: Facility[] = [
  {
    id: '1',
    name: '분당메모리얼파크',
    type: 'park',
    religion: 'none',
    address: '경기도 성남시 분당구 새나리로 79',
    lat: 37.4042,
    lng: 127.1475,
    priceRange: '1,000~3,000만원',
    rating: 4.6,
    reviewCount: 342,
    imageUrl: 'https://images.unsplash.com/photo-1605218427360-644b94e339e1?q=80&w=800&auto=format&fit=crop',
    description: '서울 강남에서 20분 거리, 울창한 숲과 예술적인 조각품이 어우러진 도심 속 추모공원입니다. 유명 연예인과 예술가들이 잠들어 있는 명소로 유명합니다.',
    features: ['넓은 주차장', '조각 공원', '편리한 교통', '매점'],
    phone: '031-704-6351',
    prices: [
      { type: '봉안묘 (2위)', price: '1,500만원' },
      { type: '봉안담 (개인)', price: '500만원' },
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1596627848624-94b6113b299e?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1464243936082-27352f23246f?q=80&w=800&auto=format&fit=crop'
    ],
    reviews: [
      { id: 'r1', space_id: '1', user_id: 'mock1', userName: '김철수', rating: 5, date: '2023.10.15', content: '가족들과 함께 방문했는데 관리가 정말 잘 되어 있어서 좋았습니다.' }
    ],
    naverBookingUrl: 'https://booking.naver.com/booking/13/bizes/123456'
  },
  {
    id: '2',
    name: '시안가족추모공원',
    type: 'complex',
    religion: 'none',
    address: '경기도 광주시 오포읍 문형산길 85',
    lat: 37.3325,
    lng: 127.1852,
    priceRange: '1,200~4,000만원',
    rating: 4.8,
    reviewCount: 521,
    imageUrl: 'https://images.unsplash.com/photo-1595842858223-b684cb402b85?q=80&w=800&auto=format&fit=crop',
    description: '여의도 공원의 3.5배 규모를 자랑하는 대규모 가족 봉안묘 시설입니다. 전통과 현대의 조화가 돋보입니다.',
    features: ['대형 주차장', '셔틀버스 운행', '제례실', '휴게 라운지'],
    phone: '1577-1024',
    prices: [
      { type: '가족 봉안묘 (4위)', price: '2,200만원' },
      { type: '평장묘', price: '1,300만원' },
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1623165246232-a56763595cb6?q=80&w=800&auto=format&fit=crop'
    ],
    reviews: [
      { id: 'r1', space_id: '2', user_id: 'mock4', userName: '최민수', rating: 5, date: '2023.11.02', content: '시설이 굉장히 크고 웅장합니다.' }
    ]
  },
  {
    id: '3',
    name: '에덴낙원',
    type: 'charnel',
    religion: 'christian',
    address: '경기도 이천시 마장면 서이천로 449-79',
    lat: 37.2341,
    lng: 127.5085,
    priceRange: '500~2,000만원',
    rating: 4.9,
    reviewCount: 189,
    imageUrl: 'https://images.unsplash.com/photo-1548625361-120063251410?q=80&w=800&auto=format&fit=crop',
    description: '호텔급 시설을 갖춘 기독교 전용 봉안당입니다. 부활 소망을 담은 밝고 아름다운 공간입니다.',
    features: ['부활 교회', '티하우스', '호텔 에덴', '기독교 특화'],
    phone: '031-645-9191',
    prices: [
      { type: '일반실 (개인)', price: '600만원' },
      { type: '특별실 (부부)', price: '1,500만원' },
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1445052344078-7b9668383a8b?q=80&w=800&auto=format&fit=crop'
    ],
    reviews: [
      { id: 'r1', space_id: '3', user_id: 'mock6', userName: 'Hannah Kim', rating: 5, date: '2023.12.01', content: '납골당이 아니라 휴양지 같은 느낌이에요.' }
    ],
    naverBookingUrl: 'https://booking.naver.com/booking/13/bizes/654321'
  },
  {
    id: '4',
    name: '용인 평온의 숲',
    type: 'natural',
    religion: 'none',
    address: '경기도 용인시 처인구 이동읍 평온의숲로 77',
    lat: 37.1652,
    lng: 127.2455,
    priceRange: '100~300만원',
    rating: 4.5,
    reviewCount: 850,
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-dfd8d395ea6c?q=80&w=800&auto=format&fit=crop',
    description: '용인도시공사가 운영하는 최첨단 종합 장사 시설입니다. 화장부터 안치까지 원스톱으로 가능합니다.',
    features: ['화장장', '장례식장', '자연장지', '공영 시설'],
    phone: '031-329-5900',
    prices: [
      { type: '자연장 (용인시민)', price: '100만원' },
      { type: '봉안당 (관외)', price: '300만원' },
    ],
    galleryImages: [
      'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?q=80&w=800&auto=format&fit=crop'
    ],
    reviews: []
  },
  {
    id: '5',
    name: '유토피아 추모관',
    type: 'charnel',
    religion: 'none',
    address: '경기도 안성시 일죽면 화곡길 130',
    lat: 37.0655,
    lng: 127.3552,
    priceRange: '300~1,500만원',
    rating: 4.4,
    reviewCount: 410,
    imageUrl: 'https://images.unsplash.com/photo-1618357874943-4e6f4967397e?q=80&w=800&auto=format&fit=crop',
    description: '영화와 드라마 촬영지로 유명한 유럽풍의 고급 실내 봉안당입니다. 안중근 의사 추모비가 위치해 있습니다.',
    features: ['영화 촬영지', 'IT 추모 시스템', '유럽풍 설계', '철저한 보안'],
    phone: '1588-2030',
    prices: [
      { type: '일반단', price: '400만원' },
      { type: '로얄단', price: '1,200만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '6',
    name: '국립하늘숲추모원',
    type: 'natural',
    religion: 'none',
    address: '경기도 양평군 양동면 양동로 756',
    lat: 37.4855,
    lng: 127.6552,
    priceRange: '200~300만원',
    rating: 4.7,
    reviewCount: 215,
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=800&auto=format&fit=crop',
    description: '국내 1호 국립 수목장림으로 산림청이 직접 관리합니다. 대자연 속에서의 영면을 도와드립니다.',
    features: ['국립 시설', '수목장 특화', '산책로', '자연 회귀'],
    phone: '031-775-6637',
    prices: [
      { type: '수목장 (가족목)', price: '230만원' },
      { type: '수목장 (공동목)', price: '70만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '7',
    name: '청아공원',
    type: 'charnel',
    religion: 'christian',
    address: '경기도 고양시 일산동구 은마길 129',
    lat: 37.6955,
    lng: 126.7952,
    priceRange: '400~1,500만원',
    rating: 4.5,
    reviewCount: 1205,
    imageUrl: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop',
    description: '대한민국 대표 기독교 봉안당으로 20년 역사를 자랑합니다. 밝고 따뜻한 분위기가 특징입니다.',
    features: ['기독교 전용관', '꽃축제', '유명인 안치', '풍부한 경험'],
    phone: '031-977-9911',
    prices: [
      { type: '일반실', price: '450만원' },
      { type: 'VIP실', price: '1,200만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '8',
    name: '용인공원',
    type: 'complex',
    religion: 'none',
    address: '경기도 용인시 처인구 모현읍 새래로 158-33',
    lat: 37.3055,
    lng: 127.2052,
    priceRange: '1,500~5,000만원',
    rating: 4.7,
    reviewCount: 630,
    imageUrl: 'https://images.unsplash.com/photo-1623788257007-84f509d7328d?q=80&w=800&auto=format&fit=crop',
    description: '45만 평의 국내 최대 규모 공원 묘원입니다. 모든 형태의 장묘가 가능한 명당 자리입니다.',
    features: ['최대 규모', '명당 입지', '수목장/봉안묘', '셔틀 운행'],
    phone: '031-334-3333',
    prices: [
      { type: '매장묘', price: '2,800만원' },
      { type: '수목장', price: '600만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '9',
    name: '분당 스카이캐슬',
    type: 'charnel',
    religion: 'none',
    address: '경기도 광주시 오포읍 신현로 116',
    lat: 37.3655,
    lng: 127.1352,
    priceRange: '500~2,500만원',
    rating: 4.6,
    reviewCount: 290,
    imageUrl: 'https://images.unsplash.com/photo-1590623663045-8164d1421f66?q=80&w=800&auto=format&fit=crop',
    description: '호텔급 인테리어와 최상의 서비스를 제공하는 프리미엄 봉안당입니다. 고급스러운 안치 시설을 갖추고 있습니다.',
    features: ['프리미엄 시설', '호텔급 내부', '철저한 온도관리', 'VIP 상담'],
    phone: '031-712-2000',
    prices: [
      { type: '일반단', price: '500만원' },
      { type: '노블레스', price: '2,500만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '10',
    name: '인천가족공원',
    type: 'complex',
    religion: 'none',
    address: '인천광역시 부평구 평온로 158',
    lat: 37.4725,
    lng: 126.7255,
    priceRange: '50~400만원',
    rating: 4.2,
    reviewCount: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1498522271744-cdd435c13f24?q=80&w=800&auto=format&fit=crop',
    description: '인천광역시가 운영하는 종합 장사 시설로 산림과 바다가 어우러진 도심 평안의 휴식처입니다.',
    features: ['공영 시설', '대규모 공원', '화장시설 연계', '다양한 안치'],
    phone: '032-510-1900',
    prices: [
      { type: '봉안당 (관내)', price: '100만원' },
      { type: '자연장', price: '60만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '11',
    name: '인천 해양장 (바다장)',
    type: 'sea',
    religion: 'none',
    address: '인천광역시 중구 연안부두로 36',
    lat: 37.4525,
    lng: 126.5985,
    priceRange: '40~150만원',
    rating: 4.7,
    reviewCount: 156,
    imageUrl: 'https://images.unsplash.com/photo-1505118380757-91f5f45d8de0?q=80&w=800&auto=format&fit=crop',
    description: '푸른 바다로 떠나는 마지막 여행, 인천 연안부두에서 진행되는 품격 있는 해양장 서비스입니다.',
    features: ['전용 선박', '해양 추모식', '환경 보호 방식', '24시간 예약'],
    phone: '1577-4444',
    prices: [
      { type: '일반 해양장', price: '50만원' },
      { type: 'VIP 전용선', price: '150만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '12',
    name: '부산 연안 해양장',
    type: 'sea',
    religion: 'none',
    address: '부산광역시 해운대구 달맞이길 62',
    lat: 35.1612,
    lng: 129.1585,
    priceRange: '50~200만원',
    rating: 4.8,
    reviewCount: 98,
    imageUrl: 'https://images.unsplash.com/photo-1516108317508-6788f6a160e6?q=80&w=800&auto=format&fit=crop',
    description: '부산 앞바다의 푸른 물결 위에서 고인을 자유롭게 보내드리는 고품격 해양 장례 서비스입니다.',
    features: ['해운대 출항', '프리미엄 요트', '추모 음악', '유골 산골'],
    phone: '051-744-1004',
    prices: [
      { type: '요트 해양장', price: '80만원' },
      { type: '가족 전용선', price: '180만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '13',
    name: '서라벌공원묘원 (불교)',
    type: 'park',
    religion: 'buddhism',
    address: '경상북도 경주시 외동읍 서라벌로 123',
    lat: 35.7525,
    lng: 129.3585,
    priceRange: '800~2,500만원',
    rating: 4.6,
    reviewCount: 142,
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?q=80&w=800&auto=format&fit=crop',
    description: '천년 고도 경주의 정기를 받은 불교 전용 추모 묘원입니다. 사찰과 연계된 49제 시스템을 갖추고 있습니다.',
    features: ['사찰 연계', '불교식 추모', '명당 입지', '석물 조각'],
    phone: '054-744-0000',
    prices: [
      { type: '불교 봉안묘', price: '1,500만원' },
      { type: '부도탑', price: '상담 후 결정' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '14',
    name: '무지개추모공원',
    type: 'charnel',
    religion: 'none',
    address: '경기도 김포시 통진읍 옹정리 123',
    lat: 37.6855,
    lng: 126.6585,
    priceRange: '300~1,000만원',
    rating: 4.3,
    reviewCount: 88,
    imageUrl: 'https://images.unsplash.com/photo-1560185121-06014470d9bd?q=80&w=800&auto=format&fit=crop',
    description: '서울 서부권에서 접근이 용이한 김포의 현대식 봉안당입니다. 밝은 실내 채광과 쾌적한 시설을 자랑합니다.',
    features: ['서울 근접', '밝은 실내', '합리적 가격', '무인 보안'],
    phone: '031-988-0000',
    prices: [
      { type: '일반실', price: '350만원' },
      { type: '부부실', price: '700만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '15',
    name: '동화경모공원',
    type: 'park',
    religion: 'none',
    address: '경기도 파주시 탄현면 헤이리로 12-34',
    lat: 37.7855,
    lng: 126.6985,
    priceRange: '1,500~3,500만원',
    rating: 4.5,
    reviewCount: 230,
    imageUrl: 'https://images.unsplash.com/photo-1447752875253-b7f58cb02083?q=80&w=800&auto=format&fit=crop',
    description: '파주 헤이리 마을 인근의 수려한 경관을 자랑하는 공원묘지입니다. 북녘 땅이 보이는 평화로운 안식처입니다.',
    features: ['전망 좋은 입지', '넓은 광장', '사이버 추모관', '연계 체험'],
    phone: '031-944-0000',
    prices: [
      { type: '봉안묘 (12위)', price: '2,800만원' },
      { type: '평장묘', price: '1,500만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '16',
    name: '양평 무궁화공원',
    type: 'natural',
    religion: 'none',
    address: '경기도 양평군 서종면 국수리 456',
    lat: 37.5255,
    lng: 127.3585,
    priceRange: '400~1,200만원',
    rating: 4.4,
    reviewCount: 65,
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb773b09?q=80&w=800&auto=format&fit=crop',
    description: '양평의 맑은 산세 아래 조성된 프리미엄 수목장 시설입니다. 잘 가꿔진 나무 아래 고인을 모십니다.',
    features: ['수목장 전문', '양평 산세', '일대일 관리', '가족목 특화'],
    phone: '031-772-0000',
    prices: [
      { type: '가족 수목장', price: '800만원' },
      { type: '공동 수목장', price: '450만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '17',
    name: '천안공원묘원',
    type: 'park',
    religion: 'none',
    address: '충청남도 천안시 동남구 광덕면 광덕로 567',
    lat: 36.6855,
    lng: 127.1085,
    priceRange: '1,000~2,500만원',
    rating: 4.1,
    reviewCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?q=80&w=800&auto=format&fit=crop',
    description: '중부권 최대 규모의 역사 깊은 묘원입니다. 풍수지리상 뛰어난 명당 자리로 손꼽힙니다.',
    features: ['명당 입지', '전통 방식', '체계적 관리', '석물 조각'],
    phone: '041-567-0000',
    prices: [
      { type: '매장묘', price: '2,000만원' },
      { type: '봉안묘', price: '1,200만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '18',
    name: '광주 영락공원',
    type: 'complex',
    religion: 'none',
    address: '광주광역시 북구 효령동 산 12',
    lat: 35.2255,
    lng: 126.8885,
    priceRange: '30~200만원',
    rating: 4.0,
    reviewCount: 920,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=800&auto=format&fit=crop',
    description: '호남권 최대의 공영 장사 시설로 깨끗한 자연 경관과 합리적인 이용료가 특징입니다.',
    features: ['공영 시설', '원스톱 서비스', '시민 할인', '넓은 녹지'],
    phone: '062-572-4384',
    prices: [
      { type: '봉안당', price: '150만원' },
      { type: '자연장', price: '40만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '19',
    name: '울산 하늘공원',
    type: 'complex',
    religion: 'none',
    address: '울산광역시 울주군 삼동면 보삼길 121',
    lat: 35.4855,
    lng: 129.1585,
    priceRange: '100~350만원',
    rating: 4.6,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?q=80&w=800&auto=format&fit=crop',
    description: '전국 최초의 친환경 도심 공원형 종합 장사 시설입니다. 갤러리와 카페 등 편의시설이 우수합니다.',
    features: ['갤러리 시설', '고급 카페테리아', '최첨단 화장', '친환경 운영'],
    phone: '052-255-3800',
    prices: [
      { type: '봉안시설', price: '200만원' },
      { type: '수목장', price: '120만원' },
    ],
    galleryImages: [],
    reviews: []
  },
  {
    id: '20',
    name: '약사사 추모관 (불교)',
    type: 'charnel',
    religion: 'buddhism',
    address: '경기도 부천시 성주로 123',
    lat: 37.4755,
    lng: 126.7855,
    priceRange: '300~1,500만원',
    rating: 4.3,
    reviewCount: 74,
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bbaa?q=80&w=800&auto=format&fit=crop',
    description: '도심 속 사찰 내에 위치하여 매일 스님의 독경 소리가 들리는 평온한 불교 봉안당입니다.',
    features: ['사찰 내 위치', '매일 독경', '가족 제례 지원', '편리한 접근성'],
    phone: '032-612-0000',
    prices: [
      { type: '일반 안치단', price: '450만원' },
      { type: 'VIP 안치단', price: '1,500만원' },
    ],
    galleryImages: [],
    reviews: []
  }
];

export const RESERVATION_DEPOSIT = 100000;
export const BANK_ACCOUNT = "신한 110-123-456789 (주식회사 아톰케어)";

export const PET_FUNERAL_COMPANIES: FuneralCompany[] = [
  {
    id: 'pet_fc_1',
    name: '포포즈',
    rating: 5.0,
    reviewCount: 290,
    imageUrl: '/images/pet_logos/pet_fc_1.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"],
    ai_price_summary: {
      basic_5kg: "20만원",
      basic_10kg: "25만원",
      large_kg: "40만원 부터",
      shroud: "10만원",
      stone: "20만원",
      pickup_basic: "5만원",
      pickup_long: "10만원~"
    }
  },
  {
    id: 'pet_fc_2',
    name: '21그램',
    rating: 4.9,
    reviewCount: 280,
    imageUrl: '/images/pet_logos/pet_fc_2.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"],
    ai_price_summary: {
      basic_5kg: "22만원",
      basic_10kg: "27만원",
      large_kg: "45만원 부터",
      shroud: "10만원",
      stone: "25만원",
      pickup_basic: "5만원",
      pickup_long: "10만원~"
    }
  },
  {
    id: 'pet_fc_3',
    name: '펫포레스트',
    rating: 4.8,
    reviewCount: 270,
    imageUrl: '/images/pet_logos/pet_fc_3.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_4',
    name: '스카이펫',
    rating: 4.8,
    reviewCount: 260,
    imageUrl: '/images/pet_logos/pet_fc_4.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_5',
    name: '굿바이엔젤',
    rating: 4.8,
    reviewCount: 250,
    imageUrl: '/images/pet_logos/pet_fc_5.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_6',
    name: '펫바라기',
    rating: 4.7,
    reviewCount: 240,
    imageUrl: '/images/pet_logos/pet_fc_6.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_7',
    name: '모두펫상조',
    rating: 4.7,
    reviewCount: 230,
    imageUrl: '/images/pet_logos/pet_fc_7.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_8',
    name: '펫문',
    rating: 4.6,
    reviewCount: 220,
    imageUrl: '/images/pet_logos/pet_fc_8.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_9',
    name: '파트라슈',
    rating: 4.5,
    reviewCount: 210,
    imageUrl: '/images/pet_logos/pet_fc_9.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  },
  {
    id: 'pet_fc_10',
    name: '해피엔딩',
    rating: 4.5,
    reviewCount: 200,
    imageUrl: '/images/pet_logos/pet_fc_10.png',
    description: '반려동물을 위한 품격 있는 이별',
    features: ["장례식장 직영", "24시간 상담"],
    phone: '1588-0000',
    priceRange: '문의',
    benefits: ["반려동물 장례 용품 할인"]
  }
];
