
-- 1. 기존 테이블 삭제 (타입 변경을 위해)
DROP TABLE IF EXISTS user_likes;

-- 2. 테이블 새로 생성 (Clerk 호환성 확보)
create table user_likes (
  id bigint generated by default as identity primary key,
  user_id text not null, -- UUID 대신 TEXT 사용 (Clerk ID 지원)
  target_id text not null,
  category text default 'sangjo',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, target_id) 
);

-- 3. RLS 활성화
alter table user_likes enable row level security;

-- 4. 정책 생성 (Clerk JWT 연동)
-- auth.uid() 대신 auth.jwt() ->> 'sub'를 사용하여 TEXT 형태의 ID 비교

create policy "Users can view their own likes" 
on user_likes for select 
using ( (auth.jwt() ->> 'sub') = user_id );

create policy "Users can insert their own likes" 
on user_likes for insert 
with check ( (auth.jwt() ->> 'sub') = user_id );

create policy "Users can delete their own likes" 
on user_likes for delete 
using ( (auth.jwt() ->> 'sub') = user_id );

-- 5. 인덱스 설정
CREATE INDEX IF NOT EXISTS idx_user_likes_user_id ON user_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_user_likes_target_id ON user_likes(target_id);
