-- reviews 테이블 생성 (존재하지 않을 경우에만)
CREATE TABLE IF NOT EXISTS public.reviews (
    id bigint generated by default as identity primary key,
    memorial_space_id bigint references public.memorial_spaces(id) on delete cascade not null,
    user_name text not null,      -- 작성자 이름
    content text not null,        -- 후기 내용
    rating int default 5,         -- 별점
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 활성화 (테이블이 새로 생성된 경우를 대비)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 정책 생성 (존재 여부 확인 후 생성 - 오류 방지)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'reviews' AND policyname = 'Reviews are viewable by everyone'
    ) THEN
        CREATE POLICY "Reviews are viewable by everyone" ON public.reviews FOR SELECT USING ( true );
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'reviews' AND policyname = 'Users can create reviews'
    ) THEN
        CREATE POLICY "Users can create reviews" ON public.reviews FOR INSERT WITH CHECK ( true );
    END IF;
END
$$;
