-- 1. Ensure public.users(clerk_id) is unique so it can be referenced
-- This block checks if the constraint exists, and adds it if not.
DO $$ 
BEGIN 
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_clerk_id_key') THEN
    ALTER TABLE public.users ADD CONSTRAINT users_clerk_id_key UNIQUE (clerk_id);
  END IF;
END $$;

-- 2. Drop existing table to clean up mismatched types/constraints
DROP TABLE IF EXISTS public.partner_inquiries;

-- 3. Recreate table with FOREIGN KEY to public.users(clerk_id)
create table public.partner_inquiries (
  id bigint generated by default as identity primary key,
  user_id text references public.users(clerk_id) on delete set null, -- FK to public.users
  target_facility_id bigint references public.memorial_spaces(id) on delete set null,
  company_name text not null,
  manager_name text not null,
  phone text not null,
  email text,
  type text not null,
  business_gov_id_image text,
  status text not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS
alter table public.partner_inquiries enable row level security;

-- 5. Policies
create policy "Enable insert for all"
  on public.partner_inquiries for insert
  with check (true);

create policy "Enable select for all"
  on public.partner_inquiries for select
  using (true);

create policy "Enable update for all"
  on public.partner_inquiries for update
  using (true);

-- 6. Comment
COMMENT ON TABLE public.partner_inquiries IS 'Fixed table with FK to public.users';
