-- ⚠️ PHASE 2 (Attempt 6 - ADD USERS TABLE): EXECUTE IN SUPABASE SQL EDITOR
-- Purpose: Migrate ID columns to TEXT (Clerk Compatibility)
-- Fix: Adds 'public.users' table to the migration list because Frontend uses it.

BEGIN;

-- =================================================================
-- 0. PRE-FLIGHT: DROP ALL POLICIES
-- =================================================================
-- Drop policies on 'users' too!
DROP POLICY IF EXISTS "Clerk User Insert" ON users;
DROP POLICY IF EXISTS "Clerk User Select" ON users;
DROP POLICY IF EXISTS "Clerk User Update" ON users;

DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN 
        SELECT schemaname, tablename, policyname
        FROM pg_policies
        WHERE tablename IN ('memorial_spaces', 'profiles', 'consultations', 'partner_inquiries', 'favorites', 'leads', 'reviews', 'facility_submissions', 'user_likes', 'users')
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', r.policyname, r.schemaname, r.tablename);
        RAISE NOTICE 'Dropped policy: %', r.policyname;
    END LOOP;
END $$;


-- =================================================================
-- 1. DROP CONSTRAINTS
-- =================================================================
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;
ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey;
ALTER TABLE memorial_spaces DROP CONSTRAINT IF EXISTS memorial_spaces_owner_user_id_fkey;
ALTER TABLE partner_inquiries DROP CONSTRAINT IF EXISTS partner_inquiries_user_id_fkey;
ALTER TABLE favorites DROP CONSTRAINT IF EXISTS favorites_user_id_fkey;
ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_user_id_fkey;
ALTER TABLE leads DROP CONSTRAINT IF EXISTS leads_user_id_fkey1;
ALTER TABLE consultations DROP CONSTRAINT IF EXISTS consultations_user_id_fkey;
ALTER TABLE user_likes DROP CONSTRAINT IF EXISTS user_likes_user_id_fkey;
ALTER TABLE facility_submissions DROP CONSTRAINT IF EXISTS facility_submissions_applicant_user_id_fkey;

-- Users table constraint?
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_id_fkey;


-- =================================================================
-- 2. MIGRATE COLUMNS TO TEXT
-- =================================================================

-- Migrate PROFILES
DO $$ BEGIN
    ALTER TABLE profiles ALTER COLUMN id DROP DEFAULT; 
    ALTER TABLE profiles ALTER COLUMN id TYPE text USING id::text;
    EXCEPTION WHEN undefined_table THEN
        -- Keep creating logic in case
        CREATE TABLE profiles (id text PRIMARY KEY, email text, full_name text, role text DEFAULT 'user', created_at timestamptz DEFAULT now());
END $$;

-- Migrate USERS (The source of 403 error)
-- useAuthSync.ts uses: clerk_id (text), email, name, image_url, role, phone_number
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'users') THEN
        -- Make sure clerk_id exists and is TEXT
        -- If table exists, we assume it's the right one.
        -- We won't change 'id' if it's serial, unless it's UUID linked to auth.
        -- But let's make sure RLS is ready.
        NULL; -- Just a placeholder, main work is RLS below.
    ELSE
        -- Create it if missing (Frontend expects it)
        CREATE TABLE users (
            id bigint generated by default as identity primary key,
            clerk_id text unique not null,
            email text,
            name text,
            image_url text,
            role text default 'user',
            phone_number text,
            created_at timestamptz default now()
        );
    END IF;
END $$;


ALTER TABLE memorial_spaces ALTER COLUMN owner_user_id TYPE text;
ALTER TABLE partner_inquiries ALTER COLUMN user_id TYPE text;
ALTER TABLE favorites ALTER COLUMN user_id TYPE text;
ALTER TABLE leads ALTER COLUMN user_id TYPE text;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'consultations' AND column_name = 'user_id') THEN
        ALTER TABLE consultations ALTER COLUMN user_id TYPE text;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'user_likes' AND column_name = 'user_id') THEN
        ALTER TABLE user_likes ALTER COLUMN user_id TYPE text;
    END IF;
END $$;

DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'facility_submissions' AND column_name = 'applicant_user_id') THEN
        ALTER TABLE facility_submissions ALTER COLUMN applicant_user_id TYPE text;
    END IF;
END $$;


-- =================================================================
-- 3. FIX FUNCTIONS (RPCs)
-- =================================================================
DROP FUNCTION IF EXISTS approve_partner_and_grant_role(uuid, uuid);
DROP FUNCTION IF EXISTS approve_partner_and_grant_role(uuid, text);
DROP FUNCTION IF EXISTS is_super_admin();

CREATE OR REPLACE FUNCTION approve_partner_and_grant_role(
    inquiry_id UUID,
    target_user_id TEXT 
) RETURNS VOID AS $$
BEGIN
    UPDATE partner_inquiries SET status = 'approved' WHERE id = inquiry_id;
    -- Upsert to profiles
    IF target_user_id IS NOT NULL THEN
        INSERT INTO profiles (id, role) VALUES (target_user_id, 'facility_admin')
        ON CONFLICT (id) DO UPDATE SET role = 'facility_admin';
    END IF;
    -- Also update 'users' table role if it exists?
    -- useAuthSync.ts uses 'users' table.
    -- Ideally, we should unify, but for now let's just update 'profiles' as that's what is_super_admin checks.
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION is_super_admin()
RETURNS BOOLEAN AS $$
BEGIN
    RETURN EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = (select auth.uid()::text) 
        AND role = 'super_admin'
    );
EXCEPTION 
    WHEN OTHERS THEN RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- =================================================================
-- 4. RESTORE SAFELIST RLS POLICIES
-- =================================================================

ALTER TABLE memorial_spaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE partner_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE consultations ENABLE ROW LEVEL SECURITY;
ALTER TABLE facility_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

-- USERS Table Policies (Fix for useAuthSync 403)
CREATE POLICY "Clerk User Select" ON users FOR SELECT TO public USING (true);
CREATE POLICY "Clerk User Insert" ON users FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Clerk User Update" ON users FOR UPDATE TO public USING (true);


-- Other Policies
CREATE POLICY "Clerk Safe Insert" ON memorial_spaces FOR INSERT TO public WITH CHECK (owner_user_id IS NOT NULL AND length(owner_user_id) > 5 AND owner_user_id LIKE 'user_%');
CREATE POLICY "Clerk Inquiry Insert" ON partner_inquiries FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Clerk Lead Insert" ON leads FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Clerk Favorite Insert" ON favorites FOR INSERT TO public WITH CHECK (user_id IS NOT NULL AND length(user_id) > 5);
CREATE POLICY "Clerk Submission Insert" ON facility_submissions FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Clerk Like Insert" ON user_likes FOR INSERT TO public WITH CHECK (user_id IS NOT NULL);
CREATE POLICY "Clerk Consultation Insert" ON consultations FOR INSERT TO public WITH CHECK (true);

-- Read Policies
CREATE POLICY "Public Read Facilities" ON memorial_spaces FOR SELECT TO public USING (true);
CREATE POLICY "Public Read Favorites" ON favorites FOR SELECT TO public USING (true);
CREATE POLICY "Public Read Reviews" ON reviews FOR SELECT TO public USING (true);
CREATE POLICY "Public Read Profiles" ON profiles FOR SELECT TO public USING (true);

-- Permissions
GRANT EXECUTE ON FUNCTION approve_partner_and_grant_role(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION approve_partner_and_grant_role(uuid, text) TO anon;
GRANT EXECUTE ON FUNCTION is_super_admin() TO anon;
GRANT EXECUTE ON FUNCTION is_super_admin() TO authenticated;

COMMIT;

SELECT 'Migration including USERS table completed successfully.' as result;
