-- 1. 기존 favorites 테이블 삭제 (충돌 방지)
DROP TABLE IF EXISTS favorites;

-- 2. favorites 테이블 새로 생성
-- user_id: Clerk ID (text, 예: user_2rg...) 저장
-- facility_id: Facilities 테이블 ID (uuid) 참조
CREATE TABLE favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id text NOT NULL, -- UUID가 아닌 Text로 변경 (Clerk ID 지원)
    facility_id uuid REFERENCES facilities(id) ON DELETE CASCADE NOT NULL,
    created_at timestamptz DEFAULT now(),
    
    -- 유저당 하나의 시설만 즐겨찾기 가능
    UNIQUE(user_id, facility_id)
);

-- 3. RLS (보안 정책) 활성화
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

-- 4. 정책 설정 (Clerk JWT와 연동)
-- auth.uid()는 UUID만 반환하므로, Clerk ID(Text)를 가져오기 위해 auth.jwt() ->> 'sub' 사용

-- 조회 (Select)
CREATE POLICY "Users can view their own favorites"
ON favorites FOR SELECT
USING (
    user_id = (select auth.jwt() ->> 'sub')
);

-- 추가 (Insert)
CREATE POLICY "Users can add their own favorites"
ON favorites FOR INSERT
WITH CHECK (
    user_id = (select auth.jwt() ->> 'sub')
);

-- 삭제 (Delete)
CREATE POLICY "Users can remove their own favorites"
ON favorites FOR DELETE
USING (
    user_id = (select auth.jwt() ->> 'sub')
);

-- 권한 부여
GRANT ALL ON favorites TO authenticated;
GRANT ALL ON favorites TO service_role;
