export const Z_INDEX = {
    SIDE_MENU: 60,
    FACILITY_SHEET: 200,
    SANGJO_SHEET: 220,
    SANGJO_COMPARISON: 230,
    SANGJO_CONSULTATION: 300,
    SANGJO_CONTRACT: 400,
    CONSULTATION_FORM: 500,
    LOADING_SPINNER: 999,
} as const;
