
-- 1. 테이블 생성
create table if not exists user_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  target_id text not null,
  category text default 'sangjo',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, target_id) 
);

-- 2. RLS 활성화
alter table user_likes enable row level security;

-- 3. 정책 초기화 및 생성
DROP POLICY IF EXISTS "Users can view their own likes" ON user_likes;
DROP POLICY IF EXISTS "Users can insert their own likes" ON user_likes;
DROP POLICY IF EXISTS "Users can delete their own likes" ON user_likes;

create policy "Users can view their own likes" 
on user_likes for select 
using (auth.uid() = user_id);

create policy "Users can insert their own likes" 
on user_likes for insert 
with check (auth.uid() = user_id);

create policy "Users can delete their own likes" 
on user_likes for delete 
using (auth.uid() = user_id);

-- [추가 추천] 4. 성능 향상을 위한 인덱스 설정
-- 내 찜 목록을 빨리 불러오기 위해
CREATE INDEX IF NOT EXISTS idx_user_likes_user_id ON user_likes(user_id);
-- 업체가 찜 개수(통계)를 빨리 세기 위해
CREATE INDEX IF NOT EXISTS idx_user_likes_target_id ON user_likes(target_id);
