-- 1. 상조 회사 테이블에 필요한 컬럼 추가
ALTER TABLE public.memorial_spaces 
ADD COLUMN IF NOT EXISTS description text,        -- 회사 소개
ADD COLUMN IF NOT EXISTS gallery_images text[],   -- 갤러리 이미지 URL 배열
ADD COLUMN IF NOT EXISTS features text[];         -- 주요 특징 (태그 배열)

-- 2. 후기 테이블 생성
CREATE TABLE IF NOT EXISTS public.reviews (
    id bigint generated by default as identity primary key,
    memorial_space_id bigint references public.memorial_spaces(id) on delete cascade not null,
    user_name text not null,      -- 작성자 이름
    content text not null,        -- 후기 내용
    rating int default 5,         -- 별점
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RLS 정책 (선택 사항: 필요 시 추가)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone" 
ON public.reviews FOR SELECT 
USING ( true );

CREATE POLICY "Users can create reviews" 
ON public.reviews FOR INSERT 
WITH CHECK ( true ); -- 실제 서비스 시 auth.uid() 체크 등 필요
